# Generated by Django 2.0.3 on 2018-06-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('username', models.CharField(max_length=20, verbose_name='账号')),
                ('psw', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'verbose_name': '顾客',
                'verbose_name_plural': '顾客',
            },
        ),
        migrations.CreateModel(
            name='BuyerGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='购买数量')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Buyer',
                                            verbose_name='买主编号')),
            ],
            options={
                'verbose_name': '购物情况',
                'verbose_name_plural': '购物情况',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('quantity', models.IntegerField(default=0, verbose_name='库存')),
                ('image',
                 models.ImageField(height_field=100, upload_to='goods_img', verbose_name='图片', width_field=100)),
                ('unit_price', models.FloatField(verbose_name='单价')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('username', models.CharField(max_length=20, verbose_name='账号')),
                ('psw', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'verbose_name': '商家',
                'verbose_name_plural': '商家',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Seller',
                                             verbose_name='所属卖家编号')),
            ],
            options={
                'verbose_name': '商店',
                'verbose_name_plural': '商店',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Shop',
                                    verbose_name='所属商店'),
        ),
        migrations.AddField(
            model_name='buyergoods',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Goods',
                                    verbose_name='商品编号'),
        ),
    ]
